import { Roboto } from "next/font/google";
import Footer from "./component/Footer";
import Navbar from "./component/Navbar";
import "./globals.css";
import Store from "./provider/Store";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Store>
          <Navbar />
          {children}
          <Footer />
        </Store>
      </body>
    </html>
  );
}
