import { Roboto } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Footer from "./component/Footer";
import Navbar from "./component/Navbar";
import "./globals.css";
import Store from "./provider/Store";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Store>
          <Navbar />
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              className: "",
              duration: 4000,
              style: {
                top: "3rem",
                right: "1rem",
                boxShadow: "0 4px 8px rgba(0,0,0,0.1)",
              },
              success: {
                duration: 3000,
              },
            }}
          />
          <Footer />
        </Store>
      </body>
    </html>
  );
}
